### ISSUE TITLE
Define which quotation mark is/are allowed

### ISSUE THREAD

**Issue by abmagil** [ember-template-lint/ember-cli-template-lint#120]
Straightforward enough- a rule (or pair of rules) defining which types of quotation marks (`'` vs. `"`) are allowed in templates.

**Comment by rwjblue** [comment]
@abmagil - Absolutely agreed!  Work is in progress over in https://github.com/rwjblue/ember-template-lint/pull/42.

**Comment by abmagil** [comment]
Oh excellent! Looking there, I only saw support for forcing double quotes,
but not for selecting which quote is preferred. Did I miss a
commit/comment?

Looking forward to the next version! Thanks!

**Comment by Turbo87** [comment]
implemented by https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/quotes.md
