### ISSUE TITLE
Disallow inline 'style' attribute in html or hbs

### ISSUE THREAD

**Issue by shijistar** [ember-template-lint/ember-cli-template-lint#134]
Im most projects, we recommend that using css to style the dom elements. But some ones may prefer to write inline style rules, because it's just quick! I would be wonderful if we have a rule that totally disallow inline `style` rules. And it would be even more wonderful if we can add inline directive comment to disable   a rule for some rare reasons.

**Comment by shijistar** [comment]
Maybe I need to post in project `ember-template-lint`

**Comment by kellyselden** [comment]
This is resolved in ember-template-lint v0.6.4
