### ISSUE TITLE
Template liting error:  -:-  error  Cannot read property 'length' of undefined undefined

### ISSUE THREAD

**Issue by ondrejsevcik** [ember-template-lint/ember-cli-template-lint#325]
Hi, I came across a weird issue where I got this failing test for my template

```
 -:-  error  Cannot read property 'length' of undefined  undefined
Expected: true
Result: false
```

after a bit of investigation, I was able to narrow the issue down to this template code
```hbs
<div class={{"my-class"}}></div>
```

I admit, that there is no need to wrap string within those brackets so I removed it in my code and it's working as expected. Anyway, it was working fine also with brackets and finding where the issue was took me some time. It would be better to handle this case and maybe provide better error message.

**Comment by rwjblue** [comment]
Thanks for reporting! Definitely seems like a bug here to me though. We need to try to figure out which plugin is causing the error and update it to properly handle this case....

**Comment by rwjblue** [comment]
I believe this has been fixed, happy to reopen if I am mistaken...
