### ISSUE TITLE
Reenabling template rule causes template lint tests to fail

### ISSUE THREAD

**Issue by blamens** [ember-template-lint/ember-cli-template-lint#337]
Since today I am getting failing linter tests in my test suite on templates that reenable the `bare-strings` rule.

This is causing failing tests:
```
{{!-- template-lint-disable bare-strings --}}
<i class="material-icons">folder_open</i>
{{!-- template-lint-enable bare-strings --}}
```

This works:
```
{{!-- template-lint-disable bare-strings --}}
<i class="material-icons">folder_open</i>
```

**Comment by scottkidder** [comment]
looks like bare-strings has been changed to no-bare-strings among other rule name changes in ember-template-lint.

**Comment by rwjblue** [comment]
I believe this was fixed by a prior release, closing for now (happy to reopen if I’m mistaken)...
