### ISSUE TITLE
Deprecation logic negation

### ISSUE THREAD

**Issue by Exelord** [ember-template-lint/ember-cli-template-lint#358]
<img width="1196" alt="screen shot 2018-07-30 at 20 37 17" src="https://user-images.githubusercontent.com/1469375/43436251-63d45ca0-9438-11e8-9edf-921f5a61d958.png">

**Comment by Exelord** [comment]
`bare-strings` is deprecated in favor of `no-bare-strings` but it is still required in case we are using ember-intl.

We should change the requirement to use `no-bare-strings` as well.

**Comment by rwjblue** [comment]
Can you confirm you are on the latest version? The latest version emits `no-bare-strings` (not `bare-strings` like in the screenshot).

https://github.com/ember-template-lint/ember-cli-template-lint/blob/f997e0d1b612bb8f0db7dc82455a46559a8a806a/broccoli-template-linter.js#L145

**Comment by Exelord** [comment]
So sorry! You are right! That was on 0.7.5 not 0.7.6!
