### ISSUE TITLE
Cannot read property 'original' of undefined  undefined

### ISSUE THREAD

**Issue by cah-danmonroe** [ember-template-lint/ember-cli-template-lint#387]
When using an unless block with else and there is no empty line between the `else` and the next child-block, you get `Cannot read property 'original' of undefined  undefined`.  Swapping the logic and using if blocks works fine.

```
{{#unless showStuff}}
  No Stuff
{{else}}
  {{#child-block}}
    Linting error: Cannot read property 'original' of undefined  undefined
  {{/child-block}}
{{/unless}}
```

```
{{#unless showStuff}}
  No Stuff
{{else}}

  {{#child-block}}
    Expected linting error: Using an else block with unless should be avoided.  simple-unless
  {{/child-block}}
{{/unless}}
```

```
{{#if showStuff}}
  {{#child-block}}
    Stuff
  {{/child-block}}
{{else}}
  This works as expected
{{/if}}
```

**Comment by lifeart** [comment]
@rwjblue cannot reproduce this in masted due to 
![image](https://user-images.githubusercontent.com/1360552/51816555-15785a00-22d8-11e9-833a-4e42c3ce7c53.png)

**Comment by bmish** [comment]
Yeah I think I fixed this https://github.com/ember-template-lint/ember-template-lint/pull/592

**Comment by rwjblue** [comment]
Thank you!
