### ISSUE TITLE
Number of indented spaces detected incorrectly

### ISSUE THREAD

**Issue by annaemu** [ember-template-lint/ember-cli-template-lint#416]
I have installed "ember-cli-template-lint": "1.0.0-beta.2" running on "ember-cli": "2.18.2". I receive the below error:
42:25  error  Incorrect indentation for `component` beginning at L17:C10. Expected `{{/component}}` ending at L42:C25 to be at an indentation of 10 but was found at 11.  block-indentation

This is incorrect because a manual count of the indentation at that line does show 10. The entire component is below (using the html editor here breaks the formatting sorry):
https://codepad.co/snippet/ABo0fstu

For reference this seems to be as a result of the full stop within the component name (truncated reference below):
`{{#complex/tables/table-simple
  as |table|
}}
  {{table.head}}
  {{#table.body as |_rows columns click rowChange rowInput _sharedOptions|}}
  {{/table.body}}
{{/complex/tables/table-simple}}`

**Comment by initram** [comment]
Do you still see this error? I am unable to reproduce it using the current version.

**Comment by rwjblue** [comment]
Going to close. If you are still running into it could you open a new issue over on ember-template-lint/ember-template-lint?
