### ISSUE TITLE
Add option for specifying template-lintrc

### ISSUE THREAD

**Issue by jhitchins88** [ember-template-lint/ember-cli-template-lint#435]
Currently, there's no way to pass an option specifying your `template-lintrc` file.  I would like there to be an option to specify a specific file and location.

I have a branch ready on my fork if this is something you'd like.

**Comment by rwjblue** [comment]
This was implemented in https://github.com/ember-template-lint/ember-template-lint/pull/528, but has not been released yet.

**Comment by jhitchins88** [comment]
Sweet, thanks.  I'll close.
