### ISSUE TITLE
add rule to warn for unsupported handlebars syntax

### ISSUE THREAD

**Issue by efx** [ember-template-lint/ember-cli-template-lint#437]
I have some handlebars syntax in my application that "works", but is "wrong".
[Twiddle](https://ember-twiddle.com/07c76e285823a864ecfd1a59dc754705?openFiles=templates.application.hbs%2C)
```hbs
<p>some user name {{this.list.[0].name}}</p>
```

@locks and @rwjblue proposed adding a template rule to warn/error before any deprecations. ( see [ember-cli discord](https://discordapp.com/channels/480462759797063690/486548111221719040) on 2/06/19)

**Comment by Alonski** [comment]
I usually replace this code with using an `objectAt` helper.

**Comment by Alonski** [comment]
Any reason this was closed? @efx

**Comment by efx** [comment]
@Alonski indeed: I reopened in https://github.com/ember-template-lint/ember-template-lint/issues/787. I think that repository contains the actual parser and related logic whereas this one is simply the runner.
