### ISSUE TITLE
Update dependency to support Dynamic styles

### ISSUE THREAD

**Issue by jathanasiou** [ember-template-lint/ember-cli-template-lint#529]
Currently the dependency for https://github.com/ember-template-lint/ember-template-lint is a little outdated.
https://github.com/ember-template-lint/ember-cli-template-lint/blob/72d60ac2106953220750a5fba6fdffa16b969fd2/package.json#L38

Because of this, the `allowDynamicStyles` property that was [added in 1.2.0](https://changelogs.md/github/rwjblue/ember-template-lint/) is not supported, and one cannot add this option in order to legalize inline styles.

Please consider updating the `ember-template-lint` depedency to support this.

**Comment by rwjblue** [comment]
We allow the most recent version already. I’m happy to accept a PR to update, but you can update yourself as well (the only reason you aren’t getting the latest already is your repos package-lock.json or yarn.lock).

**Comment by dcyriller** [comment]
Closed in #533
