### ISSUE TITLE
Doesn't lint files in /app/components

### ISSUE THREAD

**Issue by lstrzebinczyk** [ember-template-lint/ember-cli-template-lint#551]
So it's now possible (and encouraged, I think) to co-locate your component files, pushing some of the applications templates to /components directory.
Template lint doesn't seem to have access to those files, and he probably should.
What would be required to enable that? I might be able to spend some time getting linter up to speed.

**Comment by rwjblue** [comment]
I think in general, we should work towards migrating folks to using `yarn lint:hbs` (which runs the `ember-template-lint` executable directly, and can run on all of your directories).

**Comment by lstrzebinczyk** [comment]
@rwjblue And what about the tests integration? Currently this is extremely handy, that I don't have to run anything additional, and as long as I check my tests suite, Ember has me covered on linter side.

**Comment by boris-petrov** [comment]
@lstrzebinczyk - how did you work around this problem? I just hit the same issue. In addition to test integration, I also used to get warnings in `ember server` but now these are gone as well.

@rwjblue - what's the suggested solution to both problems? I don't get errors in `ember server` and I don't have test support... I think I shouldn't have migrated to using co-location.

**Comment by lstrzebinczyk** [comment]
@boris-petrov I didn't, I still have no coverage for component template files: ).

**Comment by dcyriller** [comment]
https://github.com/ember-template-lint/ember-cli-template-lint/pull/553 might fix your issue

**Comment by boris-petrov** [comment]
@dcyriller - `ember-cli-template-lint@2.0.0` still doesn't lint template files in the `app/components` directory. Can someone tell us how to proceed? Is this going to be fixed any time soon or should we go back to the classic layout?

**Comment by dcyriller** [comment]
I agree with @rwjblue said.

Using directly ember-template-lint had significant benefits including build time improvements. This is why I did it quite a long time ago.

I’ve released a v2 mainly to keep the repo infrastructure up to date to be able to land bug fixes if someone wants to open PR.

**Comment by boris-petrov** [comment]
@dcyriller - what do you mean by "using directly ember-template-lint"?

Running manually the linter in CI (in addition to `ember test`) is almost fine but how do you develop when errors are not shown in `ember server`? Write a bunch of templates, then run the linter manually, fix the errors, repeat the same every half an hour?

**Comment by lstrzebinczyk** [comment]
I'm fine with using template lint "directly", if that is the suggested way going forward, but what does that mean specifically? Will `ember-cli-template-lint` be deprecated, will running template lint with `ember server` and tests be deprecated? If that is the case, what about ember-cli-eslint?

**Comment by dcyriller** [comment]
By using "directly ember-template-lint" I mean: setup your editor to display template-lint errors in real time ([a useful link](https://discuss.emberjs.com/t/are-there-editor-integrations-for-ember-template-lint/14686))  and / or add git-hooks to automatically run linters

Also, as you mentioned, setup `yarn lint:hbs` (or `npm run lint:hbs`) to run in CI.

I personnaly setup my editor to display lint errors in real time.
Some collegues of mine use the second approach. In this gist, you'll find what their config look like: https://gist.github.com/dcyriller/c484738bf4e66aa8f674054675efcd6e

Also, you might have a look to this [merged RFC](https://github.com/emberjs/rfcs/blob/master/text/0121-remove-ember-cli-eslint.md). Its goal is to remove ember-cli-eslint from the default blueprint. But the idea is the same for ember-cli-template-lint.

**Comment by boris-petrov** [comment]
@dcyriller - OK, fair enough, I don't particularly like or agree that this is the right way to go, but I guess it is already "done" so that's that. Just one more question - is the same true for `ember-cli-stylelint` and `ember-cli-typescript`? That is, should they be removed and the things they "wrap" (`stylelint` and `TypeScript`) be used separately?

**Comment by lstrzebinczyk** [comment]
Allright, thank you for clarifying that for me, I will adjust my codebase appriopriately: ). As far as I'm concerned, I've got my answers and the issue is good for closing.

**Comment by dcyriller** [comment]
I don't know much the project but I would apply the same reasoning to all linting libraries, incl. ember-cli-stylelint.

`ember-cli-typescript` does something different, I think it's still needed.
