### ISSUE TITLE
Prepare a v2

### ISSUE THREAD

**Issue by dcyriller** [ember-template-lint/ember-cli-template-lint#560]
I'm following up here a discussion we had with @rwjblue in https://github.com/ember-template-lint/ember-cli-template-lint/pull/557 to release a v2.

That PR's goal was to drop NodeJs versions to fix Dependabot upgrades. Now that it is done, what others changes should be done to cut a v2 release?

You suggested a blueprints update @rwjblue. I'm unsure how they should be changed though. Blueprints currently use `recommended` set of rule. Do you think they should use `octane` from now on?

Also, we'll have to upgrade `ember-template-lint` to v2.

TODO:
- update blueprints
- upgrade ember-template-lint to v2

side-note: https://github.com/ember-cli/ember-cli/pull/9009

**Comment by rwjblue** [comment]
Ya, the blueprints update that I was referring to was essentially `ember-cli-update` (updating packages to latest, updating the repo structure, etc).

**Comment by dcyriller** [comment]
I have two PRs for v2.

The first one makes use of ember-template-lint's `octane` set: https://github.com/ember-template-lint/ember-cli-template-lint/pull/568

The second one updates the project: https://github.com/ember-template-lint/ember-cli-template-lint/pull/567

**Comment by dcyriller** [comment]
@rwjblue I've released v2 with the above-mentioned changes.

**Comment by dcyriller** [comment]
I doesn't fix the pod / co-located components issue.
