### ISSUE TITLE
[META] Linting for obvious accessibility issues.

### ISSUE THREAD

**Issue by nathanhammond** [ember-template-lint/ember-cli-template-lint#99]
We discussed that we can catch accessibility issues and more in this addon. Introducing David Peter, @sarenji, from the Ember A11y team. 😄 Amusingly, the ember-a11y addon came out of the same Zesty Hack Day as ember-cli-template-lint.
- [x] `{{action}}` on non-default-interactive elements (https://github.com/rwjblue/ember-template-lint/issues/41). 
- [x] `img` elements without an `alt=` specified (https://github.com/rwjblue/ember-template-lint/issues/45).
- [ ] ???

**Comment by rwjblue** [comment]
Sounds awesome, let's add issues in ember-template-lint repo for each new rule. I'd like each issue to include 'good' and 'bad' examples (as well as some info on what makes a given thing bad).

**Comment by Robdel12** [comment]
I got one going: https://github.com/rwjblue/ember-template-lint/issues/41

Let me know if there's any more I can add to the issue. Maybe we can make a template out of it for future rules?

**Comment by sarenji** [comment]
I added an attempt of my own here: #45. I used @Robdel12's as a template :)

**Comment by Turbo87** [comment]
both action items are addressed. closing :)
